# This workflow runs the OpenAPI linting and validation script.
name: OpenAPI Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository so the job can access your files
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up Node.js, which is needed to run npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a Long-Term Support (LTS) version of Node.js
          cache: 'npm'      # Speeds up future runs by caching dependencies

      # 3. Installs the linting dependencies from your package.json file
      - name: Install dependencies
        run: npm install

      # 4. Runs your lint.sh script to validate the OpenAPI spec
      - name: Run OpenAPI linters
        run: ./lint.sh
